image: python:3.7-slim-buster

before_script:
  - pip install -r requirements.txt

pages:
  stage: deploy
  script:
  - jupyter-book build -W .
  - mv _build/jupyter_execute .
  - mv _build/html public
  artifacts:
    paths:
    - public
  only:
  - master
