title: "3IA Health Data Hub - Workshop on heterogeneous data and Federated Learning"
logo: "assets/img/logo.jpg"
only_build_toc_files: true
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "README.md"]
execute:
  execute_notebooks: "off"