title: "3IA Health Data Hub - Workshop on heterogeneous data and Federated Learning"
logo: "assets/img/logo.jpg"
only_build_toc_files: true
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "README.md"]

repository:
  url                       : https://gitlab.inria.fr/ssilvari/flhd
  branch                    : master


launch_buttons:
  notebook_interface: jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)