title: "3IA Health Data Hub - Workshop on heterogeneous data and Federated Learning"
author: Santiago Silva, Marco Lorenzi, Irene Balelli, Yann Fraboni, Andrea Scenacheribbe, Luigi Antelmi
logo: "assets/img/logo.jpg"
only_build_toc_files: true
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", "README.md"]

execute:
  execute_notebooks         : "off"

repository:
  url: https://gitlab.inria.fr/ssilvari/flhd
  path_to_book              : "/"  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links
  
html:
  use_repository_button: True
  extra_footer: "<a target=\"_blank\" href=\"https://team.inria.fr/epione/fr/\">EPIONE</a>"